server:
  port: 8081
  servlet:
    # 项目的路径，配置如下之后，它的路径为http:localhost:8081/subway
    context-path: /subway
#    数据库
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/whsubway
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#   redis -->没用上
redis:
  port: 6379
  password:
  cluster:
    node: localhost
  lettuce:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 20
logging:
  level:
    com.dormitory.mapper: debug
